# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_test/myobject.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf_test/myobject.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cprotobuf_test/myobject.proto\x12\x08tutorial\"\xbe\x01\n\x08MyObject\x12\x11\n\tPackageID\x18\x01 \x02(\x05\x12\x10\n\x08PersonID\x18\x02 \x02(\x05\x12\x0c\n\x04Name\x18\x03 \x02(\t\x12\x34\n\tInventory\x18\x04 \x03(\x0b\x32!.tutorial.MyObject.InventoryEntry\x12\x17\n\x0f\x43urrentLocation\x18\x05 \x02(\t\x1a\x30\n\x0eInventoryEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01'
)




_MYOBJECT_INVENTORYENTRY = _descriptor.Descriptor(
  name='InventoryEntry',
  full_name='tutorial.MyObject.InventoryEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tutorial.MyObject.InventoryEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tutorial.MyObject.InventoryEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=233,
)

_MYOBJECT = _descriptor.Descriptor(
  name='MyObject',
  full_name='tutorial.MyObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PackageID', full_name='tutorial.MyObject.PackageID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PersonID', full_name='tutorial.MyObject.PersonID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='tutorial.MyObject.Name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Inventory', full_name='tutorial.MyObject.Inventory', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CurrentLocation', full_name='tutorial.MyObject.CurrentLocation', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MYOBJECT_INVENTORYENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=233,
)

_MYOBJECT_INVENTORYENTRY.containing_type = _MYOBJECT
_MYOBJECT.fields_by_name['Inventory'].message_type = _MYOBJECT_INVENTORYENTRY
DESCRIPTOR.message_types_by_name['MyObject'] = _MYOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyObject = _reflection.GeneratedProtocolMessageType('MyObject', (_message.Message,), {

  'InventoryEntry' : _reflection.GeneratedProtocolMessageType('InventoryEntry', (_message.Message,), {
    'DESCRIPTOR' : _MYOBJECT_INVENTORYENTRY,
    '__module__' : 'protobuf_test.myobject_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.MyObject.InventoryEntry)
    })
  ,
  'DESCRIPTOR' : _MYOBJECT,
  '__module__' : 'protobuf_test.myobject_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.MyObject)
  })
_sym_db.RegisterMessage(MyObject)
_sym_db.RegisterMessage(MyObject.InventoryEntry)


_MYOBJECT_INVENTORYENTRY._options = None
# @@protoc_insertion_point(module_scope)
